### PR TITLE
Bump to allow ruby 3.1

### PR DESCRIPTION
**Pull request by colinxfleming**
Ruby 3.1 is out, so bumping this to allow the version, test it in the matrix, increment the version, etc.

(That said, it looks like this is smashing into an upstream `Psych::DisallowedClass` error, so I think this might be more a notice of intent than a working PR right now.)

### CODE REVIEW

**Comment by colinxfleming** [comment]
(Also, thank you all for maintaining this library, it's great)

**Comment by jzhang2-civis** [comment]
Hi Colin! Thanks for submitting a PR.

Could you provide a link to the error you're seeing? How can we help?

**Comment by xmunoz** [comment]
The error comes up when running `bundle install`:
```
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
ruby_audit-2.0.0 requires ruby version < 3.1, >= 2.5, which is incompatible with the current version, ruby 3.1.0p0
```

**Comment by xmunoz** [comment]
Looks like your building on a xenial image in travis. Might try bumping the distro image to focal to see if that gets the build green.

**Comment by xmunoz** [comment]
> How can we help?
@jzhang2-civis We'd like upgrade our project to ruby 3.1, but can not because this gem is one of our dependencies, and it currently specifies compatibility with `ruby version < 3.1`.

**Comment by jzhang2-civis** [comment]
@colinxfleming Could you please try the focal image as @xmunoz suggested?

https://docs.travis-ci.com/user/reference/overview/#the-amd64-builds

If that works, could you please also add to the [changelog](https://github.com/civisanalytics/ruby_audit/blob/master/CHANGELOG.md), as specified by our [contribution guidelines](https://github.com/civisanalytics/ruby_audit/blob/master/CONTRIBUTING.md)?

Thanks!

**Comment by nevans** [comment]
Regarding the "upstream Psych::DisallowedClass error" mentioned in the pr description:

The release notes for bundler-audit lists a Psych incompatibility they've fixed.  PR #22 fixes that error for me. Does #22 fix it for you too, @colinxfleming?

(I tested using `bundle exec rake spec` locally.  The travis image will still need to be upgraded for CI to install ruby 3.1.)

**Comment by jzhang2-civis** [comment]
Hi there, I left a comment on PR #24, but it's relevant here: https://github.com/civisanalytics/ruby_audit/pull/24#issuecomment-1021464676

Long story short, Travis / RVM don't support Ruby 3.1 yet.

**Comment by xmunoz** [comment]
This can be closed in lieu of #25

**Comment by jzhang2-civis** [comment]
Hi there, Ruby Audit 2.1.0 has been released. @xmunoz was kind enough to contribute a change that allows Ruby 3.1 and adds it to the testing matrix. Please try out the release and let me know if it works for you!

**Comment by colinxfleming** [comment]
thanks much @jzhang2-civis and @xmunoz !

**Pull request closed without merging**
