### PR TITLE
Support ruby 3.1

### PR DESCRIPTION
**Pull request by xmunoz**
This PR is meant to supercede https://github.com/civisanalytics/ruby_audit/pull/21

### CODE REVIEW

**Comment by xmunoz** [comment]
Opened an issue in the community forum: https://travis-ci.community/t/travis-cannot-find-ruby-3-1-using-rvm/12624

**Comment by xmunoz** [comment]
Honestly, Travis has had continually diminishing support and stability over the past few years. The easier way to fix this issue might be migrating CI to Github Actions.

**Comment by jzhang2-civis** [comment]
Hi there. I was curious about this too and I did some research---

I don't think rvm officially supports Ruby 3.1 yet, nor does anything else I've seen in Travis. So the image may not need upgrading to get to Ruby 3.1.
https://docs.travis-ci.com/user/languages/ruby/#Supported-Ruby-Versions
https://rubies.travis-ci.org/
https://github.com/rvm/rvm/releases

My understanding is that you're right that there are other options, and our team agrees that it would be nice to use something else.
CircleCI appears to support Ruby 3.1.
https://circleci.com/developer/images/image/cimg/ruby

GitHub Actions seems like it's based off of a repo that specifically does setup for Ruby, and includes Ruby 3.1.
https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ruby#specifying-the-ruby-version

I think we have 2 options:
1. You (or another contributor) could make the change to another continuous integration. We're very happy to review and would really appreciate it.
2. Wait until Travis + RVM support it Ruby 3.1. It was released fairly recently, so maybe support will be coming soon.

**Comment by xmunoz** [comment]
> I don't think rvm officially supports Ruby 3.1 yet, nor does anything else I've seen in Travis. So the image may not need upgrading to get to Ruby 3.1.
https://docs.travis-ci.com/user/languages/ruby/#Supported-Ruby-Versions
https://rubies.travis-ci.org/
https://github.com/rvm/rvm/releases
`
I'm not sure that is true. There was [a PR](https://github.com/rvm/rvm/pull/5169/files) merged last month for 3.1 support, and I'm able to install it locally with `rvm install ruby-3.1.0`.

**Comment by xmunoz** [comment]
@jzhang2-civis I've commited a Github Actions test workflow. I think you now need to enable Github Actions in the settings of this repository.

**Comment by jzhang2-civis** [comment]
@xmunoz Hi there, sorry for the delayed response. GitHub Actions should now be enabled. Can you see / do anything with that test workflow?

**Comment by xmunoz** [comment]
New workflows are disabled on forks by default. How to proceed from here is up to you. You can merge this PR and roll it back if it doesn't do what you expect. You can also break it up so that the Github action workflow file is merged before the Travis config is removed.

**Comment by jzhang2-civis** [comment]
Hi @xmunoz, my understanding is that you have the GitHub Action workflow file set up correctly, so it's not entirely clear why it's not working.

I don't currently have the bandwidth, but I will take a look at adding GitHub Actions as the next update for this repo.

Thank you for your patience!

**Pull request closed without merging**
